# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.srcs/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0.xci
# IP: The module: 'ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/bd_5b68.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_0/bd_5b68_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_1/bd_5b68_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_2/bd_5b68_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_3/bd_5b68_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_4/bd_5b68_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_5/bd_5b68_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_6/bd_5b68_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_7/bd_5b68_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_8/bd_5b68_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_9/bd_5b68_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_1/bd_5b68_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_1/bd_5b68_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_5/bd_5b68_s00a2s_0_ooc.xdc

# XDC: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_6/bd_5b68_sarn_0_ooc.xdc

# XDC: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_7/bd_5b68_srn_0_ooc.xdc

# XDC: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_8/bd_5b68_m00s2a_0_ooc.xdc

# XDC: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.srcs/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0.xci
# IP: The module: 'ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/bd_5b68.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_0/bd_5b68_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_1/bd_5b68_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_2/bd_5b68_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_3/bd_5b68_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_4/bd_5b68_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_5/bd_5b68_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_6/bd_5b68_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_7/bd_5b68_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_8/bd_5b68_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_9/bd_5b68_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_1/bd_5b68_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_1/bd_5b68_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_5/bd_5b68_s00a2s_0_ooc.xdc

# XDC: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_6/bd_5b68_sarn_0_ooc.xdc

# XDC: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_7/bd_5b68_srn_0_ooc.xdc

# XDC: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/bd_0/ip/ip_8/bd_5b68_m00s2a_0_ooc.xdc

# XDC: /home/users/edoardo.dalessio/code/av_omega/VersalAutomationTemplate/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp_inst_0/ip/ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_inst_0_axi_ic_axi_noc_kernel0_S01_AXI_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
